### PR TITLE
geocsv by AK

### PR DESCRIPTION
**Pull request by akanik**
My attempt at geocsv integration.

### CODE REVIEW

**Comment by mhkeller** [comment]
So excited for this! 

To save some hassle, using https://github.com/mapbox/csv2geojson could be a good way to avoid having to do the formatting and parsing yourself.

**Comment by akanik** [comment]
Sweet! Thanks for the resource.

**Comment by ebrelsford** [comment]
Glad to help with it too, let's fix #18.

**Comment by akanik** [comment]
Yeah @ebrelsford!

**Pull request closed without merging**
