### PR TITLE
fixes nav link

### PR DESCRIPTION
**Pull request by 1wheel**

### CODE REVIEW

**Comment by ebrelsford** [comment]
The docs are generated using [documentation.js](http://documentation.js.org/), so this change would be overwritten next time the docs are generated.

**Comment by mhkeller** [comment]
Thanks for the quick help Adam! We ended up patching our base theme to regen: https://github.com/mhkeller/indian-ocean/issues/21

Might some of the [other issues](https://github.com/mhkeller/indian-ocean/issues) interest you...

**Comment by 1wheel** [comment]
whoops, sorry about that. 

Library is looking like a nice alternative to copying and pasting the same bit of reading/writing csv code every time I need to scrape something!

**Comment by mhkeller** [comment]
that was exactly the motivation :)

**Pull request closed without merging**
